ignore curl error (#33)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -85,24 +85,26 @@ runs:
       run: |
         set +x  # Turn off command echoing
         printf '%.0s-' {1..80}
-        printf '\n'
-        response=$(curl -s https://api.github.com/repos/soos-io/soos-sca-github-action/releases/latest)
-        if [ $? -eq 0 ]; then
-          latest_tag=$(echo "$response" | grep -oP '"tag_name": "\K(.*)(?=")')
-          current_tag=$(echo "$SOOS_ACTION_REF" | awk -F'/' '{print $NF}')
-          latest_tag_major=$(echo "$latest_tag" | awk -F'.' '{print $1}')
-          
-          echo "Your current version is: $current_tag, The latest version is: $latest_tag_major"
-          
-          if [[ "$current_tag" != "$latest_tag_major"* ]]; then
-            echo "This action is outdated or using a commit reference. Please update to use the latest major version tag: $latest_tag_major"
-          elif [[ "$current_tag" == "$latest_tag" ]]; then
-            echo "It is recommended to use the major version tag, $latest_tag_major when referencing this action."
-          elif [[ "$current_tag" != "$latest_tag_major" ]]; then
-            echo "This action is out of date. It is recommended to use the major version tag, $latest_tag_major."
+        printf '\n'        
+        response=$(curl -s https://api.github.com/repos/soos-io/soos-sast-github-action/releases/latest || true)        
+        if [ -n "$response" ]; then
+          latest_tag=$(echo "$response" | grep -oP '"tag_name": "\K(.*)(?=")')          
+          if [ -n "$latest_tag" ]; then
+            current_tag=$(echo "$SOOS_ACTION_REF" | awk -F'/' '{print $NF}')
+            latest_tag_major=$(echo "$latest_tag" | awk -F'.' '{print $1}')            
+            echo "Your current version is: $current_tag, The latest version is: $latest_tag_major"            
+            if [[ "$current_tag" != "$latest_tag_major"* ]]; then
+              echo "This action is outdated or using a commit reference. Please update to use the latest major version tag: $latest_tag_major"
+            elif [[ "$current_tag" == "$latest_tag" ]]; then
+              echo "It is recommended to use the major version tag, $latest_tag_major when referencing this action."
+            elif [[ "$current_tag" != "$latest_tag_major" ]]; then
+              echo "This action is out of date. It is recommended to use the major version tag, $latest_tag_major."
+            fi
+          else
+            echo "Couldn't check the action version. No tag_name."
           fi
         else 
-          echo "Can't check version."
+          echo "Couldn't check the action version. No response."
         fi
         printf '%.0s-' {1..80}
         printf '\n'
